spring:
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql:///mybatis-example
    username: root
    password: 51213002
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.187.101
      port: 6379
      password: 51213002
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms
# 配置mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml