# 静态资源默认路径
# classpath:/META-INF/resources/
# classpath:/resources/
# classpath:/static/
# classpath:/public/
# 自定义静态资源路径后 默认路径不再生效
spring:
  web:
    resources:
      static-locations: classpath:/web

fx:
  root:
    username: root
    password: 51213002

server:
  port: 80
  servlet:
    context-path: /feng